import os
import base64
import json
import logging
import requests
import datetime
import functions_framework
from google import genai
from google.genai import types
from google.cloud import firestore

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Initialize Firestore
db = firestore.Client()

def get_virustotal_ip_reputation(ip_address, api_key):
    """Query VirusTotal API v3 for IP Address reputation."""
    if not api_key:
        logger.warning("VirusTotal API Key not provided. Skipping IP reputation lookup.")
        return None

    url = f"https://www.virustotal.com/api/v3/ip_addresses/{ip_address}"
    headers = {"x-apikey": api_key}

    try:
        response = requests.get(url, headers=headers, timeout=10)
        if response.status_code == 200:
            data = response.json().get("data", {})
            attributes = data.get("attributes", {})
            stats = attributes.get("last_analysis_stats", {})
            
            return {
                "malicious": stats.get("malicious", 0),
                "suspicious": stats.get("suspicious", 0),
                "harmless": stats.get("harmless", 0),
                "undetected": stats.get("undetected", 0),
                "reputation": attributes.get("reputation", 0),
                "asn": attributes.get("asn", "Unknown"),
                "as_owner": attributes.get("as_owner", "Unknown"),
                "country": attributes.get("country", "Unknown")
            }
        else:
            logger.error(f"VirusTotal API error: {response.status_code} - {response.text}")
            return None
    except Exception as e:
        logger.error(f"Error querying VirusTotal: {str(e)}")
        return None

def analyze_incident_with_gemini(log_payload, vt_data, api_key):
    """Use Gemini 2.5 Flash to write L1/L2 triage summary and recommendations."""
    if not api_key:
        logger.warning("Gemini API key not found in environment. Skipping AI analysis.")
        return {
            "severity": "LOW",
            "mitre_attack": ["T1595 - Active Scanning"],
            "summary": "AI Analysis bypassed (Gemini API Key missing).",
            "recommendations": "Add GEMINI_API_KEY environment variable to enable automated AI Triage."
        }

    try:
        client = genai.Client(api_key=api_key)
        
        # Prepare the context for Gemini
        context = {
            "timestamp": datetime.datetime.utcnow().isoformat() + "Z",
            "honeypot_log": log_payload,
            "virustotal_reputation": vt_data
        }

        prompt = f"""
You are a Lead L2 Security Operations Center (SOC) Analyst. You are triaging an alert generated by a Cowrie SSH Honeypot.
Analyze the security incident details below, combine it with the VirusTotal IP reputation data, and provide a structured classification.

Incident Context:
{json.dumps(context, indent=2)}

You MUST output your response in JSON format matching the following keys exactly:
1. "severity": Must be one of ["LOW", "MEDIUM", "HIGH", "CRITICAL"].
   - LOW: Simple connection scanning, no login attempts.
   - MEDIUM: Brute-force credentials attempts (failed logins).
   - HIGH: Successful login on the honeypot but no commands run.
   - CRITICAL: Successful login AND commands/scripts executed or payloads downloaded.
2. "mitre_attack": A list of strings matching MITRE ATT&CK techniques (e.g., ["T1110.001 - Brute Force: Password Guessing", "T1059 - Command and Scripting Interpreter"]).
3. "summary": A concise plain-English summary of what the attacker did, their origin (country/ISP), and how malicious their IP is.
4. "recommendations": Concrete mitigation steps for a junior analyst to execute (e.g. block IP in firewall, scan internal assets for the same IP).

Output only the JSON block. Do not write any markdown code blocks (like ```json), introduction, or conversational filler.
"""
        response = client.models.generate_content(
            model='gemini-2.5-flash',
            contents=prompt,
            config=types.GenerateContentConfig(
                response_mime_type="application/json"
            )
        )
        
        # Parse the JSON response
        raw_text = response.text.strip()
        
        # Remove markdown code blocks if the model ignored instructions
        if raw_text.startswith("```"):
            lines = raw_text.splitlines()
            if lines[0].startswith("```json") or lines[0].startswith("```"):
                raw_text = "\n".join(lines[1:-1]).strip()
                
        ai_verdict = json.loads(raw_text)
        return ai_verdict
        
    except Exception as e:
        logger.error(f"Error calling Gemini API: {str(e)}")
        return {
            "severity": "MEDIUM",
            "mitre_attack": ["T1213 - Data from Information Repositories"],
            "summary": f"Failed to perform AI analysis. Error: {str(e)}",
            "recommendations": "Check Cloud Function logs and investigate manually."
        }

@functions_framework.cloud_event
def triage_pubsub_event(cloud_event):
    """Cloud Function entrypoint triggered by Pub/Sub log router."""
    # Retrieve API Keys from environment (populated via Secret Manager integration)
    vt_api_key = os.environ.get("VIRUSTOTAL_API_KEY")
    gemini_api_key = os.environ.get("GEMINI_API_KEY")

    # 1. Decode Pub/Sub message data
    try:
        pubsub_data = base64.b64decode(cloud_event.data["message"]["data"]).decode("utf-8")
        log_entry = json.loads(pubsub_data)
    except Exception as e:
        logger.error(f"Failed to decode Pub/Sub message: {str(e)}")
        return

    # 2. Extract payload fields
    # Cloud Logging Log Router routes the whole LogEntry object. Cowrie payload is in jsonPayload.
    json_payload = log_entry.get("jsonPayload", {})
    event_id = json_payload.get("eventid", "cowrie.unknown")
    src_ip = json_payload.get("src_ip", "0.0.0.0")
    timestamp = json_payload.get("timestamp", datetime.datetime.utcnow().isoformat() + "Z")

    logger.info(f"Processing event {event_id} from source IP {src_ip}")

    # Skip generic/noisy system connect events if they have no login activity to save VT/Gemini quota
    # Keep login failed, login success, command execution, and file downloads
    monitored_events = [
        "cowrie.login.failed",
        "cowrie.login.success",
        "cowrie.command.input",
        "cowrie.command.failed",
        "cowrie.session.file_download",
        "cowrie.session.file_upload"
    ]
    if event_id not in monitored_events:
        logger.info(f"Skipping event type {event_id} - not in scope for triage.")
        return

    # 3. Enrich with VirusTotal
    vt_data = None
    if src_ip and src_ip != "0.0.0.0":
        vt_data = get_virustotal_ip_reputation(src_ip, vt_api_key)

    # 4. Perform AI Triage
    ai_analysis = analyze_incident_with_gemini(json_payload, vt_data, gemini_api_key)

    # 5. Build Firestore security incident document
    incident_doc = {
        "timestamp": timestamp,
        "event_id": event_id,
        "src_ip": src_ip,
        "raw_payload": json_payload,
        "virustotal": vt_data,
        "ai_analysis": ai_analysis,
        "created_at": firestore.SERVER_TIMESTAMP
    }

    # Write to Firestore
    try:
        doc_ref = db.collection("incidents").document()
        doc_ref.set(incident_doc)
        logger.info(f"Successfully recorded incident {doc_ref.id} for source IP {src_ip}")
    except Exception as e:
        logger.error(f"Failed to write incident to Firestore: {str(e)}")
